# 1. Import numpy as np and see the version

In [13]:
import numpy as np
print(np.version.version)
print(np.__version__)

1.21.2
1.21.2


# 2. How to create a 1D array?

In [16]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 3. How to create a boolean array?

In [22]:
arr3D=np.full((3, 3), True, dtype=bool)
print(arr3D)

# Alternate method:
arr3DAlt=np.ones((3,3), dtype=bool)
print(arr3DAlt)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


# 4. How to extract items that satisfy a given condition from 1D array?

>1) Difficulty Level: L1 Q. Extract all odd numbers from arr Input:::::
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

>2) Desired output:::::
#> array([1, 3, 5, 7, 9])

In [34]:
arr=np.arange(10)
print(len(arr))
arr1=[]
for i in range(len(arr)):
    if i%2 != 0:
        arr1.append(i)
print(arr1)

print(arr[arr % 2 != 0])
print(arr[arr % 2 == 1])

10
[1, 3, 5, 7, 9]
[1 3 5 7 9]
[1 3 5 7 9]


# 5. How to replace items that satisfy a condition with another value in numpy array?
> Difficulty Level: L1 Q. Replace all odd numbers in arr with -1 Input:::
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

>Desired Output:::
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [35]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.where(arr % 2 !=0 , -1, arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# 6. How to replace items that satisfy a condition without affecting the original array?
>Difficulty Level: L2 Q. Replace all odd numbers in arr with -1 without changing arr Input:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

>Desired Output:
out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
out=np.where(arr%2 != 0, -1, arr)
print(out)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


# 7. How to reshape an array?
>Difficulty Level: L1 Q. Convert a 1D array to a 2D array with 2 rows Input:
np.arange(10)
#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

>Desired Output:
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])

In [51]:
arr=np.arange(10)
print(arr)

arr2D=np.reshape(arr,(2,5))
print(arr2D)


arr.reshape(2, -1)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# 8. How to stack two arrays vertically?

>Difficulty Level: L2 Q. Stack arrays a and b vertically Input
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

>Desired Output:
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

In [64]:
a = np.arange(10).reshape(2,-1)
print("Array a:",a)
b = np.repeat(1, 10).reshape(2,-1)
print("Array b:",b)

# Method 1:
print("Method 1:",np.concatenate((a,b), axis=0))

# Method 2:
print("Method 2:",np.vstack((a,b)))

# Method 3:
print("Method 3:",np.r_[a, b])

Array a: [[0 1 2 3 4]
 [5 6 7 8 9]]
Array b: [[1 1 1 1 1]
 [1 1 1 1 1]]
Method 1: [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Method 2: [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Method 3: [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


# 9.How to stack two arrays horizontally?
>Difficulty Level: L2 Q. Stack the arrays a and b horizontally. Input
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

>Desired Output:
#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [70]:
a=np.arange(10).reshape(2,-1)
print("Array a:",a)
b=np.repeat(1,10).reshape(2,-1)
print("Array b:",b)

#Method 1:
print("Method 1:",np.concatenate((a,b),axis=1))

#Method2:
print("Methd 2:",np.hstack((a,b)))

#Method3:
print("Method 3:",np.c_[a,b])

Array a: [[0 1 2 3 4]
 [5 6 7 8 9]]
Array b: [[1 1 1 1 1]
 [1 1 1 1 1]]
Method 1: [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
Methd 2: [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
Method 3: [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


# 10. How to generate custom sequences in numpy without hardcoding?
>Difficulty Level: L2 Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a. Input:
a = np.array([1,2,3])`

>Desired Output:
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [76]:
a = np.array([1,2,3])
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# 11. How to get the common items between two python numpy arrays?
>Difficulty Level: L2 Q. Get the common items between a and b Input:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

>Desired Output:
array([2, 4])

In [82]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
print("Array a:", a)
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("Array b:", b)
np.intersect1d(a,b)

Array a: [1 2 3 2 3 4 3 4 5 6]
Array b: [ 7  2 10  2  7  4  9  4  9  8]


array([2, 4])