In [2]:
# import numpy
import numpy as np

In [26]:
tests=np.random.randint(2,size=(10,3))
tests

array([[0, 0, 0],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 0],
       [1, 0, 1],
       [1, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 0]])

In [24]:
test_sums = tests.sum(axis=1)
test_sums

array([1, 1, 1, 1, 2, 0, 3, 0, 1, 1])

In [25]:
(test_sums == 0)

array([False, False, False, False, False,  True, False,  True, False,
       False])

In [32]:
# simulate 1 million tests of one die roll
tests = np.random.choice(np.arange(1, 7), size=int(10))
tests
# proportion of tests that produced an even number
(tests % 2 == 0).mean()

0.5

In [49]:
# simulate the first million die rolls
first = np.random.choice(np.arange(1,7),size=(int(100)))

# simulate the second million die rolls
second = np.random.choice(np.arange(1,7),size=(int(100)))

# proportion of tests where the 1st and 2nd die rolled the same number
print(first)
print(second)
print(first==second)
(first==second).mean()

[3 2 1 6 1 1 5 3 2 3 3 5 5 5 2 3 3 3 2 5 3 4 5 1 3 4 1 5 3 6 6 4 4 6 4 4 3
 2 4 1 5 2 1 6 1 6 1 3 1 1 6 3 2 2 1 1 4 2 1 1 3 1 3 4 6 2 1 6 6 5 1 3 6 2
 5 2 6 6 5 4 4 4 5 4 1 1 1 3 5 4 1 6 1 5 5 1 2 4 1 4]
[1 6 1 5 4 1 1 5 1 2 6 3 2 6 6 5 5 6 4 2 2 6 3 1 4 4 1 4 1 3 6 1 1 6 4 4 1
 3 1 2 6 3 2 1 3 4 6 5 1 5 5 5 1 5 2 3 1 5 1 6 4 5 6 3 2 6 6 3 4 1 6 1 3 5
 1 6 3 1 3 4 3 5 1 1 4 5 1 4 1 4 2 6 6 4 3 5 6 3 3 6]
[False False  True False False  True False False False False False False
 False False False False False False False False False False False  True
 False  True  True False False False  True False False  True  True  True
 False False False False False False False False False False False False
  True False False False False False False False False False  True False
 False False False False False False False False False False False False
 False False False False False False False  True False False False False
 False False  True False False  True False  True False False False False
 False F

0.15

In [50]:
# simulate 1 million tests of one fair coin flip
# remember, the output of these tests are the # successes, or # heads
tests = np.random.binomial(1, 0.5, int(1e6))

# proportion of tests that produced heads
(tests == 1).mean()

0.500312

### 2. Five fair coin flips produce exactly one head

In [58]:
# simulate 1 million tests of five fair coin flips
tests = np.random.binomial(5,0.5,int(100))
tests
# proportion of tests that produced 1 head
(tests == 1).mean()

0.13